import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@mantine/core/styles.css';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
        <ColorSchemeScript />
      </head>
      <body className="bg-gray-100">
          <MantineProvider>
            <Header/>
            <main className="container mx-auto p-4">
              {children}
            </main>
          </MantineProvider>
        
      </body>
    </html>
  );
}
